main/urls.py
from django.urls import path
from . import views
from main.views import show_main, create_Item, show_xml, show_json, show_xml_by_id, show_json_by_id, register, login_user, logout_user
from main.views import edit_item, delete_item, tambah_item, kurang_item, get_item_json, add_item_ajax, delete_item_ajax, create_item_flutter

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-item', create_Item, name='create_item'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-item/<int:id>', edit_item, name='edit_item'),
    path('delete/<int:id>', delete_item, name='delete_item'),
    path('tambah/<int:id>', tambah_item, name='tambah_item'),
    path('kurang/<int:id>', kurang_item, name='kurang_item'),
    path('get-item/', get_item_json, name='get_item_json'),
    path('create-item-ajax/', add_item_ajax, name='add_item_ajax'),
    path('delete-item-ajax/<int:item_id>/', delete_item_ajax, name='delete_item_ajax'),
    path('create-flutter/', create_item_flutter, name='create_item_flutter'),

]

pacil_mart/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Item(models.Model):
    name = models.CharField(max_length=255)
    date_added = models.DateField(auto_now_add=True)
    amount = models.IntegerField()
    description = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

main/forms.py
from django.forms import ModelForm
from main.models import Item

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name","amount","description"]

main/views.py
# Create your views here.
import datetime
from django.shortcuts import render
from django.http import HttpResponseRedirect
from main.forms import ItemForm
from django.urls import reverse
from main.models import Item
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseNotFound
from django.http import JsonResponse


@login_required(login_url='/login')
def show_main(request):
    items = Item.objects.filter(user=request.user)
    context = {
        'nama_aplikasi': 'Pacil Mart',
        'name' :  request.user.username,
        'kelas': 'PBP D',
        'items': items,
        'last_login': request.COOKIES['last_login'],

    }
    
    return render(request, "main.html", context)

def create_Item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        item = form.save(commit=False)
        item.user = request.user
        item.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_item.html", context)

def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def edit_item(request, id):
    item = Item.objects.get(pk = id)

    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid() and request.method == "POST":
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_item.html", context)

def delete_item(request, id):
    # Get data berdasarkan ID
    item = Item.objects.get(pk = id)
    # Hapus data
    item.delete()
    # Kembali ke halaman awal
    return HttpResponseRedirect(reverse('main:show_main'))

def tambah_item(rrequest, id):
    item = Item.objects.get(pk = id)
    item.amount += 1
    item.save()
    # Kembali ke halaman awal
    return HttpResponseRedirect(reverse('main:show_main'))

def kurang_item(rrequest, id):
    item = Item.objects.get(pk = id)
    item.amount -= 1
    item.save()
    # Kembali ke halaman awal
    return HttpResponseRedirect(reverse('main:show_main'))

def get_item_json(request):
    item_item = Item.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', item_item))

def delete_item_ajax(request, item_id):
    if request.method == 'DELETE':
        item = Item.objects.get(id=item_id)
        item.delete()
        return HttpResponse({'status': 'DELETED'}, status=200)

@csrf_exempt
def add_item_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        user = request.user

        new_item = Item(name=name, amount=amount, description=description, user=user)
        new_item.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def delete_item_ajax(request, item_id):
    if request.method == 'DELETE':
        item = Item.objects.get(id=item_id)
        item.delete()
        return HttpResponse({'status': 'DELETED'}, status=200)

@csrf_exempt
def create_item_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_item = Item.objects.create(
            user = request.user,
            name = data["name"],
            amount = int(data["amount"]),
            description = data["description"]
        )

        new_item.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_item.html
{% extends 'base.html' %} 

{% block content %}
<h1>Add New Item</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add Item"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/edit_item.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div style="background-color: rgb(171, 172, 177); text-transform: uppercase; font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; text-align: center; padding: 10px;">
    <h1>Edit Item</h1>
</div>

<div style="background-color: rgb(192, 185, 185); padding: 20px; border-radius: 20px; box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.5); text-align: center;">
    <form method="POST">
        {% csrf_token %}
        <table style="margin: 0 auto;">
            {{ form.as_table }}
            <tr>
                <td></td>
                <td>
                    <input type="submit" value="Edit Item" style="background-color: rgb(63, 57, 178); color: aliceblue; border: none; padding: 10px 20px; border-radius: 7px; cursor: pointer;">
                </td>
            </tr>
        </table>
    </form>
</div>
{% endblock %}

main/templates/login.html
{% extends 'base.html' %}
{% block meta %}
    <title>Login</title>
{% endblock meta %}
{% block content %}
{% load static %}
<style>
    /* Latar belakang dengan gambar dan efek transparansi */
    body {
        background-image: url("{% static 'BG.png' %}");
        background-size: cover;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        margin: 0;
    }

    /* Kontainer login */
    .login {
        background-color: rgba(255, 255, 255, 0.9);
        padding: 30px;
        border-radius: 100px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2);
        text-align: center;
        max-width: 400px;
        margin: 0 auto;
        /* Menambahkan margin atas dan bawah */
        margin-top: 20px;
        margin-bottom: 20px;
    }

    /* Judul */
    h1 {
        color: #333;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        margin-bottom: 20px;
    }

    /* Tombol login */
    .login_btn {
        background-color: #007BFF;
        color: #fff;
        border: none;
        padding: 12px 24px; /* Padding lebih besar */
        border-radius: 5px;
        cursor: pointer;
        margin-top: 20px; /* Tingkatkan jarak atas */
        font-size: 18px;
        transition: background-color 0.3s; /* Efek transisi hover */
    }

    .login_btn:hover {
        background-color: #0056b3; /* Warna berubah saat hover */
    }

    /* Tautan "Register Now" */
    a {
        text-decoration: none;
        color: #007BFF;
        font-weight: bold;
        transition: color 0.3s; /* Efek transisi hover */
    }

    a:hover {
        color: #0056b3; /* Warna berubah saat hover */
    }

    /* Pesan kesalahan */
    ul {
        list-style-type: none;
        padding: 0;
    }

    ul li {
        color: red;
        font-weight: bold;
        margin-bottom: 5px;
    }
</style>

<div class="login">
    <h1>Login</h1>
    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username:</td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
            <tr>
                <td>Password:</td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>
            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>
    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <p>Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a></p>
</div>
{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<style>
    body {
        font-family: 'Verdana', sans-serif;
        font-size: 16px;
        background-image: url("{% static 'PBP6.png' %}");
        background-size: cover; /* Untuk memastikan gambar latar belakang menutupi seluruh elemen body */
        background-repeat: no-repeat; /* Menghindari pengulangan gambar latar belakang */
        background-attachment: fixed;
    }

    .card-container {
        display: grid;
        grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
        gap: 20px;
    }

    .card {
        margin-top: 55px;
        background-color: rgba(97, 94, 94, 0.492);
        color: #424242;
        border-radius: 10px;
        box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.1);
        transition: transform 0.2s, box-shadow 0.2s;
        border-color: #ffffff;
        display: flex;
        justify-content: center; /* Untuk mengatur card-inner di tengah secara horizontal */
        align-items: center; /* Untuk mengatur card-inner di tengah secara vertikal */
        }

    .card:hover {
        transform: translateY(-10px);
        box-shadow: 0px 6px 12px rgba(0, 0, 0, 0.15);
    }

    .card-inner {
        background-color: #bbbbbb; /* Warna latar belakang card-inner */
        border-radius: 10px;
        padding: 30px;
        height: 90%;
        width: 80%;
    }

    #Item_cards {
        display: grid;
        grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
        gap: 20px;
    }

    .card-title {
        background-color: #333333;
        color: #aea9a9;
        border-radius: 10px;
        width: auto;
        padding: 10px;
        font-family: 'Arial', sans-serif;
    }

    .main-content {
    font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
    }

    .page-title {
    margin: 30px auto; /* Menengahkan elemen secara horizontal dan memberikan margin atas 30px */
    text-align: center;
    border-radius: 50px;
    max-width: 75%;
    background-color: rgb(171, 172, 177);
    text-transform: uppercase;
    padding: 10px;
}


    .profile-card {
        max-width: 10%;
        width: 100%;
        margin: 0 auto;
        padding: 10px;
        border-radius: 90px;
        background-color: #00000092;
        display: flex;
        justify-content: space-between;
        align-items: center;
        box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.1);
    }

    .profile-info {
        flex: 1;
        padding: 10px;
    }

    .profile-label {
    font-family:'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
    color: rgb(255, 255, 255);
    margin: 0;
    text-align: center; /* Teks berada di tengah */
    }

    .profile-value {
        font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
        color: rgb(255, 255, 255);
        margin: 0;
        font-weight: bold;
        text-align: center; /* Teks berada di tengah */
    }


    .session-info {
        text-align: center;
        background-color: rgb(255, 0, 0);
        color: white;
        padding: 10px;
        border-radius: 30px;
    }


</style>



<nav class="navbar navbar-expand-lg bg-dark">
    <div class="container">
        <div class="navbar-brand">
            <div style="width: 130px; height: 130px; border-radius: 50%; border: 3px solid #ffffff; overflow: hidden;">
                <img src="/static/PACIl MART.png" alt="Gambar Anda" style="max-width: 100%; max-height: 100%; object-fit: cover; cursor: pointer;">
            </div>
        </div>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#" style="color: aliceblue;">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#" style="color: aliceblue;">Products</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" style="color: aliceblue;" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Categories
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Electronics</a></li>
                        <li><a class="dropdown-item" href="#">Clothing</a></li>
                        <li class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Others</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#" style="color: aliceblue;">Contact</a>
                </li>
                <li class="nav-item"> <!-- Tambahkan elemen ini untuk mengisi ruang kosong di sebelah kanan -->
                </li>
            </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>        
        </div>
    </div>
</nav>


<div class="main-content">
    <h1 class="page-title">Pacil Mart Inventory.</h1>
    <div class="profile-card">
        <div class="profile-info">
            <h5 class="profile-label">Nama:</h5>
            <p class="profile-value">{{ name }}</p>

            <h5 class="profile-label">Kelas:</h5>
            <p class="profile-value">{{ kelas }}</p>
        </div>
    </div>
</div>


<div id="Item_cards" class="card-container">
    <!-- Kartu-kartu akan ditampilkan di sini -->
</div>


<div id="Item_cards"></div>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="form" onsubmit="return false;">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name" class="col-form-label">Name:</label>
                        <input type="text" class="form-control" id="name" name="name"></input>
                    </div>
                    <div class="mb-3">
                        <label for="amount" class="col-form-label">amount:</label>
                        <input type="number" class="form-control" id="amount" name="amount"></input>
                    </div>
                    <div class="mb-3">
                        <label for="description" class="col-form-label">Description:</label>
                        <textarea class="form-control" id="description" name="description"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
            </div>
        </div>
    </div>
</div>

<div class="session-info">
    <h5>Sesi terakhir login: {{ last_login }}</h5>
</div>


<div style="width: 100%; margin-top: 20px;">
    <script>
        async function getItems() {
            return fetch("{% url 'main:get_item_json' %}").then((res) => res.json());
        }

        async function displayItemsAsCards() {
            const items = await getItems();
            let htmlString = '';

        items.forEach((item, index) => {
            const itemId = item.id;
            const isLastItem = index === items.length - 1; // Cek apakah item ini adalah item terakhir
            const cardClass = isLastItem ? 'card last-item' : 'card'; // Tambahkan kelas 'last-item' jika ini adalah item terakhir
            htmlString += `
                <div class="${cardClass} mb-4">
                    <div class="card-inner" style="background-color: ${isLastItem ? 'aliceblue' : 'bold'}; border: none; border-radius: 10px; box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.1);">
                        <div class="card-body">
                            <h5 class="card-title" style="font-family: 'Verdana', sans-serif; color: ${isLastItem ? 'white' : '#ffffff'};">${item.fields.name}</h5>
                            <p class="card-text"><strong>Amount:</strong> ${item.fields.amount}</p>
                            <p class="card-text"><strong>Description:</strong> ${item.fields.description}</p>
                            <p class="card-text"><strong>Date Added:</strong> ${item.fields.date_added}</p>
                            <a href="tambah/${item.pk}" class="btn btn-secondary" style="margin-left: 3px;">+</a> ${item.fields.amount}
                            <a href="kurang/${item.pk}"class="btn btn-secondary" style="margin-right: 3px;">-</a>
                            <button data-id="${item.pk}" class="btn btn-danger btn-sm" onclick="deleteItem(this.getAttribute('data-id'))">Delete</button>
                        </div>
                    </div>
                </div>
            `;
        });

        const cardContainer = document.querySelector(".card-container");
        cardContainer.innerHTML = htmlString;
        }

        async function deleteItem(itemId) {
            const deleteUrl =  `{% url 'main:delete_item_ajax' item_id=999 %}`.replace('999', itemId);
            console.log(itemId);
            try {
                const response = await fetch(deleteUrl, {
                    method: 'DELETE',
                    headers: {
                        'X-CSRFToken': '{{ csrf_token }}'
                    }
                }).then(displayItemsAsCards)
            } catch (error) {
                console.error('Error:', error);
            }
        }


        function addItem() {
            fetch("{% url 'main:add_item_ajax' %}", {
                method: "POST",
                body: new FormData(document.querySelector('#form'))
            }).then(displayItemsAsCards);

            document.getElementById("form").reset();
            return false;
        }

        document.getElementById("button_add").onclick = addItem;

        
        displayItemsAsCards();
    </script>
</div>

<!-- Tombol "Add Item by AJAX" di atas tombol Logout -->
<div class="text-center mt-3">
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
        Add Item by AJAX
    </button>
</div>



<div class="text-center">
    <a href="{% url 'main:logout' %}">
        <button style="background-color: rgb(255, 217, 0); color: rgb(0, 0, 0); border: none; padding: 10px 20px; border-radius: 7px; cursor: pointer; margin-top: 7px;">
            Logout
        </button>
    </a>
</div>




{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}
{% load static %}
<style>
    /* Ganti warna latar belakang menjadi biru muda */
    body {
        background-image: url("{% static 'tandatanya.png' %}");
        background-size: cover;
        display: flex;
        justify-content: center; /* Pusatkan konten horizontal */
        align-items: center; /* Pusatkan konten vertikal */
        height: 100vh; /* Sesuaikan tinggi ke viewport */
        margin: 0; /* Hapus margin halaman */
    }

    /* Gaya lainnya sesuai kebutuhan Anda */
    .login {
        background-color: rgba(255, 255, 255, 0.489);
        padding: 50px;
        border-radius: 100px;
    }

    /* Atur tampilan form input dan tombol */
    form table {
        margin: 0 auto;
    }

    form table tr td {
        padding: 4px;
        text-align: left;
        font-weight: bold;
    }

    form table tr td input[type="text"],
    form table tr td input[type="password"] {
        width: 90%;
        padding: 4px;
        border: 1px solid #ccc;
        border-radius: 3px;
        text-align: left; /* Tambahkan ini untuk mengatur tampilan rata kanan */
    }

    form table tr td input[type="submit"] {
        background-color: rgb(0, 0, 0);
        color: aliceblue;
        border: none;
        padding: 10px 20px;
        border-radius: 7px;
        cursor: pointer;
    }

    /* Stil pesan kesalahan */
    ul {
        list-style: none;
        padding: 0;
        color: red;
    }
</style>

<div class="login">
    <h1 style="color: rgb(49, 46, 51); font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;">Register</h1>

    <form method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
            <tr>
                <td></td>
                <td><input type="submit" name="submit" value="Daftar" /></td>
            </tr>
        </table>
    </form>

    {% if messages %}
    <ul>
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</div>

{% endblock content %}